removed gdal pin to 3.*
Causes mixing of repos and error with gdal
ImportError: libpoppler.so.76: cannot open shared object file: No such file or directory